  br label %1
    -> overdefined
  %i.0 = phi i32 [ 1, %0 ], [ %5, %3 ]
    -> const i32 1
  %j.0 = phi i32 [ 0, %0 ], [ %6, %3 ]
    -> overdefined
  %2 = icmp slt i32 %j.0, 10
    -> overdefined
  br i1 %2, label %3, label %7
    -> overdefined
  %4 = add nsw i32 %i.0, 1
    -> const i32 2
  %5 = sub nsw i32 %4, 1
    -> const i32 1
  %6 = add nsw i32 %j.0, 1
    -> overdefined
  br label %1
    -> overdefined
  %8 = call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([7 x i8]* @.str, i32 0, i32 0), i32 %i.0, i32 %j.0)
    -> overdefined
  ret i32 0
    -> overdefined
