  %1 = icmp ne i32 %pred, 0
    -> overdefined
  br i1 %1, label %2, label %5
    -> overdefined
  %3 = add nsw i32 1, 2
    -> const i32 3
  %4 = add nsw i32 -1, %3
    -> const i32 2
  br label %10
    -> overdefined
  br label %6
    -> overdefined
  %i.0 = phi i32 [ %11, %10 ], [ 1, %5 ]
    -> const i32 1
  %j.0 = phi i32 [ %12, %10 ], [ 0, %5 ]
    -> overdefined
  %7 = icmp slt i32 %j.0, 10
    -> overdefined
  br i1 %7, label %8, label %13
    -> overdefined
  %9 = add nsw i32 %i.0, 1
    -> const i32 2
  br label %10
    -> overdefined
  %j.1 = phi i32 [ 0, %2 ], [ %j.0, %8 ]
    -> overdefined
  %k.0 = phi i32 [ %4, %2 ], [ %9, %8 ]
    -> const i32 2
  %11 = sub nsw i32 %k.0, 1
    -> const i32 1
  %12 = add nsw i32 %j.1, 1
    -> overdefined
  br label %6
    -> overdefined
  %14 = call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([7 x i8]* @.str, i32 0, i32 0), i32 %i.0, i32 %j.0)
    -> overdefined
  ret void
    -> overdefined
  call void @test(i32 0, i32 1)
    -> overdefined
  ret i32 0
    -> overdefined
