#line 2 "if-else.l.c"

#line 4 "if-else.l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[390] =
    {   0,
        0,    0,  114,  112,  111,  111,   99,  112,  105,   98,
      112,   93,   94,  103,  102,   90,  101,   97,  104,   56,
       55,   91,   87,  106,   92,  107,  110,    3,    4,    5,
        6,    7,   53,   53,   95,   96,  108,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   88,  109,   89,  100,  111,   86,    0,
       64,    0,   72,   89,   81,   73,    0,    0,   70,   78,
       68,   79,   69,   80,    0,   59,    1,    2,   71,   60,
       56,    0,    0,   56,   56,    0,   56,   55,   55,   55,
       55,   96,   88,   95,   77,   83,   85,   84,   76,   53,

        0,    0,   74,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   15,   53,
       53,   53,   53,   53,   53,   23,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   75,   82,
       64,    0,    0,    0,    0,   57,    0,    0,   65,    0,
       59,    2,    0,   60,    0,   58,   56,   56,   56,   56,
        0,   54,   55,   55,   55,   55,   67,   66,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   21,
       53,   53,   25,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,    0,
        0,    0,    0,    0,   59,    0,   60,   58,   56,    0,
        0,   54,    0,   54,   54,   55,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,    8,   53,   10,   11,
       53,   53,   53,   53,   17,   18,   53,   53,   22,   53,
       26,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   39,   53,   53,    0,    0,    0,    0,
        0,    0,   54,   54,    0,   61,   54,   54,   53,   53,
       45,   53,   53,   53,   53,   53,   53,   53,    9,   12,
       53,   53,   53,   53,   20,   53,   53,   53,   53,   30,

       53,   53,   53,   53,   53,   53,   37,   53,   53,   41,
        0,   62,    0,   63,   61,   54,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   16,   19,   24,
       53,   53,   29,   31,   32,   33,   34,   35,   53,   53,
       53,   62,   63,   53,   53,   44,   53,   53,   53,   53,
       53,   53,   53,   53,   14,   53,   53,   36,   53,   53,
       42,   43,   46,   47,   53,   53,   53,   53,   52,   13,
       27,   28,   38,   40,   53,   49,   53,   53,   48,   53,
       53,   53,   53,   53,   53,   53,   51,   50,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   34,   34,   36,   34,   37,   34,   38,
       34,   34,   39,   40,   41,   34,   34,   42,   34,   34,
       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   34,   57,   58,   59,   60,
       61,   62,   34,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[76] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    7,    7,
        1,    1,    1,    1,    1,    3,    7,    7,    7,    7,
        7,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    3,    1,    1,    8,    6,    6,    7,
        7,    7,    6,    8,    8,    8,    8,    8,    8,    9,
        8,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        8,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[400] =
    {   0,
        0,    0,  698,  699,   74,   76,  673,   75,   57,   76,
      652,  699,  699,  671,   72,  699,   73,   71,   83,  105,
       96,  669,  699,  128,  669,   68,  699,    0,    0,    0,
        0,    0,    0,   96,  699,  699,  668,  140,  625,  627,
       47,   51,   70,   48,  628,   57,  627,  635,   88,  616,
      121,  624,  629,  699,   97,  699,  699,  156,  699,  128,
      180,  143,  699,  699,  699,  699,  134,  148,  699,  699,
      699,  699,  699,  699,  668,  171,  699,    0,  699,  178,
      220,  235,  208,  177,  128,  667,  135,  262,  208,  148,
      153,  699,  699,  699,  657,  699,  699,  699,  656,    0,

      203,  635,  699,   73,  617,  616,  624,  616,  613,  608,
      617,  618,  605,  617,  604,  619,  606,  612,  598,  599,
      596,  596,  599,  596,  593,    0,  134,  597,  194,  595,
       64,  152,  599,  592,  648,  177,  176,  596,  699,  699,
      260,  646,  252,  271,    0,  699,  267,    0,  699,  288,
      699,    0,  304,  699,  250,  312,  251,  699,  614,  591,
        0,  297,  253,  699,  612,  589,  699,  699,  590,  584,
      583,  584,  582,  593,  577,  591,  575,  571,  575,  587,
      582,  570,  140,  584,  582,  578,  570,  576,  579,    0,
      565,  569,    0,  570,  567,  557,  555,  557,  559,  566,

      552,  550,  534,  544,  534,  537,  538,  540,  528,  292,
      366,  329,  412,  322,  370,  332,  416,  699,  699,  296,
      305,  325,  360,  206,  334,  699,  520,  513,  505,  498,
      507,  504,  505,  490,  502,  493,    0,  495,    0,    0,
      486,  494,  483,  490,    0,    0,  484,  481,    0,  485,
        0,  480,  480,  479,  476,  488,  477,  480,  484,  483,
      480,  470,  474,    0,  462,  474,  255,    0,  283,    0,
      458,  467,  315,  699,  407,  471,  489,  456,  453,  456,
        0,  452,  446,  452,  441,  449,  456,  452,    0,    0,
      441,  442,  431,  422,    0,  428,  408,  415,  408,    0,

      416,  413,  409,  393,  402,  403,    0,  394,  397,    0,
      475,  479,  499,  503,  699,  699,  321,  401,  398,  393,
      387,  380,  395,  387,  390,  356,  356,    0,    0,    0,
      361,  362,    0,    0,    0,    0,    0,    0,  358,  357,
      350,  699,  699,  343,  352,    0,  335,  353,  353,  336,
      329,  321,  317,  310,    0,  297,  292,    0,  303,  301,
        0,    0,    0,    0,  282,  265,  265,  246,    0,    0,
        0,    0,    0,    0,  225,    0,  226,  222,    0,  209,
      195,  103,  102,   82,   47,   20,    0,    0,  699,  561,
      570,  574,  581,  588,  597,  602,  604,  606,  608

    } ;

static yyconst flex_int16_t yy_def[400] =
    {   0,
      389,    1,  389,  389,  389,  389,  389,  390,  389,  389,
      391,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  392,  392,  392,
      392,  392,  392,  392,  389,  389,  389,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  389,  389,  389,  389,  389,  389,  390,
      389,  393,  389,  389,  389,  389,  391,  394,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  395,  389,  389,
      389,  389,  389,  389,  389,  396,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  392,

      390,  391,  389,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  389,  389,
      389,  389,  389,  390,  397,  389,  391,  398,  389,  389,
      389,  395,  389,  389,  389,  389,  389,  389,  389,  389,
      399,  396,  389,  389,  389,  389,  389,  389,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  390,
      390,  391,  391,  389,  389,  389,  389,  389,  389,  399,
      399,  389,  389,  389,  389,  389,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  390,  211,  391,  213,
      389,  389,  389,  389,  389,  389,  389,  389,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      389,  389,  389,  389,  389,  389,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  389,  389,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,    0,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389

    } ;

static yyconst flex_int16_t yy_nxt[775] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   33,   33,   33,   34,   33,   33,   33,   33,
       34,   33,   35,    4,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   33,   46,   33,   47,   33,   33,
       33,   33,   48,   49,   50,   51,   52,   53,   33,   33,
       33,   54,   55,   56,   57,   58,   58,   58,   58,   61,
       63,   64,   65,   70,  388,   75,   72,   76,   76,   76,
       76,   98,   99,   77,  115,   71,   73,   74,   78,   66,

      101,  116,  118,  102,  387,  123,   79,  117,  124,  126,
       80,  119,   88,   88,   88,   88,  127,  199,   62,   80,
      139,   81,   81,   82,   82,  101,   83,  120,  102,  121,
      169,   89,   61,   93,  200,   83,   90,  170,  122,  135,
       84,  146,  130,  131,  386,   85,   86,   83,   94,  385,
       95,   96,  132,   91,  384,  133,   83,   58,   58,  144,
      144,   90,   87,  159,  147,  147,  104,  105,  106,  140,
       85,   62,  107,   86,  108,  158,  109,   68,  110,  111,
      136,  141,  141,  165,  101,  160,  112,   76,   76,   76,
       76,  192,  157,  164,   76,   76,   76,   76,  193,  201,

      158,  150,  151,  241,  242,  166,  151,   61,  153,  154,
      163,  145,  157,  154,  202,  142,  148,  158,  164,  155,
      142,  155,  150,  151,  156,  156,  156,  156,  151,  153,
      154,  207,  205,  208,   80,  154,   81,   81,   82,   82,
      206,  277,  158,  163,  383,  143,   62,  195,  164,   80,
       83,   82,   82,   82,   82,   84,  101,  196,  197,   61,
       85,  141,  141,  278,  101,   83,  156,  156,  156,  156,
      142,   83,  382,  164,  146,   61,   80,   87,   88,   88,
       88,   88,  381,  212,  212,   85,   83,  210,  210,  380,
      146,  158,   83,  164,  379,  142,   61,   89,   62,  214,

      142,  214,   90,  378,  215,  215,  215,  215,  267,  267,
       68,  221,  377,   83,   62,  216,  158,  216,  164,   91,
      217,  217,  217,  217,  376,  143,   68,   90,  156,  156,
      156,  156,  222,  271,  223,   62,  146,  224,  215,  215,
      215,  215,  272,  218,  375,  269,  269,  218,  217,  217,
      217,  217,  374,  373,  225,  274,  372,  271,  223,  371,
      273,  370,  224,  369,  218,  274,  272,  368,  344,  218,
       61,  275,   68,  275,  274,  367,  276,  276,  276,  276,
      274,  345,  268,  268,  268,  268,  215,  215,  215,  215,
      274,  273,  268,  268,  268,  268,  268,  268,  366,  274,

      365,  151,  364,  363,  362,  151,  361,  360,  359,   62,
      358,  357,  356,  268,  268,  268,  268,  268,  268,  146,
      355,  354,  151,  276,  276,  276,  276,  151,  270,  270,
      270,  270,  217,  217,  217,  217,  353,  352,  270,  270,
      270,  270,  270,  270,  351,  350,  349,  154,  348,  347,
      346,  154,  341,  340,  339,   68,  338,  337,  336,  270,
      270,  270,  270,  270,  270,  335,  334,  333,  154,  311,
      332,  311,  331,  154,  312,  312,  312,  312,  313,  330,
      313,  329,  328,  314,  314,  314,  314,  276,  276,  276,
      276,  312,  312,  312,  312,  312,  312,  312,  312,  327,

      326,  325,  315,  324,  323,  322,  315,  321,  320,  319,
      342,  318,  317,  316,  342,  314,  314,  314,  314,  314,
      314,  314,  314,  315,  316,  310,  309,  308,  315,  307,
      306,  342,  305,  304,  343,  303,  342,  302,  343,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  343,  285,  284,  283,  282,
      343,   60,  281,   60,   60,   60,   60,   60,   60,   60,
       67,  280,   67,  279,   67,   67,   67,   67,   67,  100,
      100,  100,  100,   60,   60,  266,   60,  265,  264,   60,
       67,   67,  263,   67,  262,  261,   67,  152,  260,  152,

      152,  152,  152,  152,  152,  152,  162,  162,  162,  211,
      211,  213,  213,  220,  220,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  226,  219,  219,
      101,  209,  101,  204,  203,  198,  194,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,   68,  168,
      167,  161,  149,  138,  137,  134,  129,  128,  125,  114,
      113,  103,   97,   92,   69,   68,   59,  389,    3,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389
    } ;

static yyconst flex_int16_t yy_chk[775] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    8,
        9,    9,   10,   15,  386,   18,   17,   18,   18,   18,
       18,   26,   26,   19,   41,   15,   17,   17,   19,   10,

       34,   41,   42,   34,  385,   44,   19,   41,   44,   46,
       21,   42,   21,   21,   21,   21,   46,  131,    8,   20,
       55,   20,   20,   20,   20,   51,   21,   43,   51,   43,
      104,   21,   60,   24,  131,   20,   21,  104,   43,   51,
       20,   67,   49,   49,  384,   20,   20,   21,   24,  383,
       24,   24,   49,   21,  382,   49,   20,   58,   58,   62,
       62,   21,   20,   85,   68,   68,   38,   38,   38,   55,
       20,   60,   38,   20,   38,   87,   38,   67,   38,   38,
       51,   61,   61,   90,   61,   85,   38,   76,   76,   76,
       76,  127,   87,   91,   80,   80,   80,   80,  127,  132,

       87,   76,   76,  183,  183,   90,   76,  101,   80,   80,
       91,   62,   84,   80,  132,   61,   68,   84,   91,   83,
       61,   83,   76,   76,   83,   83,   83,   83,   76,   80,
       80,  137,  136,  137,   81,   80,   81,   81,   81,   81,
      136,  224,   84,   89,  381,   61,  101,  129,   89,   82,
       81,   82,   82,   82,   82,   81,  143,  129,  129,  267,
       81,  141,  141,  224,  141,   82,  155,  155,  155,  155,
      143,   81,  380,   89,  147,  144,   88,   81,   88,   88,
       88,   88,  378,  147,  147,   81,   82,  144,  144,  377,
      269,  157,   88,  163,  375,  141,  210,   88,  267,  150,

      141,  150,   88,  368,  150,  150,  150,  150,  210,  210,
      147,  162,  367,   88,  144,  153,  157,  153,  163,   88,
      153,  153,  153,  153,  366,  141,  269,   88,  156,  156,
      156,  156,  162,  220,  162,  210,  212,  162,  214,  214,
      214,  214,  221,  156,  365,  212,  212,  156,  216,  216,
      216,  216,  360,  359,  162,  273,  357,  220,  162,  356,
      222,  354,  162,  353,  156,  222,  221,  352,  317,  156,
      211,  223,  212,  223,  225,  351,  223,  223,  223,  223,
      273,  317,  211,  211,  211,  211,  215,  215,  215,  215,
      222,  225,  211,  211,  211,  211,  211,  211,  350,  225,

      349,  215,  348,  347,  345,  215,  344,  341,  340,  211,
      339,  332,  331,  211,  211,  211,  211,  211,  211,  213,
      327,  326,  215,  275,  275,  275,  275,  215,  213,  213,
      213,  213,  217,  217,  217,  217,  325,  324,  213,  213,
      213,  213,  213,  213,  323,  322,  321,  217,  320,  319,
      318,  217,  309,  308,  306,  213,  305,  304,  303,  213,
      213,  213,  213,  213,  213,  302,  301,  299,  217,  271,
      298,  271,  297,  217,  271,  271,  271,  271,  272,  296,
      272,  294,  293,  272,  272,  272,  272,  276,  276,  276,
      276,  311,  311,  311,  311,  312,  312,  312,  312,  292,

      291,  288,  276,  287,  286,  285,  276,  284,  283,  282,
      312,  280,  279,  278,  312,  313,  313,  313,  313,  314,
      314,  314,  314,  276,  277,  266,  265,  263,  276,  262,
      261,  312,  260,  259,  314,  258,  312,  257,  314,  256,
      255,  254,  253,  252,  250,  248,  247,  244,  243,  242,
      241,  238,  236,  235,  234,  314,  233,  232,  231,  230,
      314,  390,  229,  390,  390,  390,  390,  390,  390,  390,
      391,  228,  391,  227,  391,  391,  391,  391,  391,  392,
      392,  392,  392,  393,  393,  209,  393,  208,  207,  393,
      394,  394,  206,  394,  205,  204,  394,  395,  203,  395,

      395,  395,  395,  395,  395,  395,  396,  396,  396,  397,
      397,  398,  398,  399,  399,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  192,  191,  189,  188,  187,  186,
      185,  184,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  166,  165,  160,  159,
      142,  138,  135,  134,  133,  130,  128,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  102,   99,
       95,   86,   75,   53,   52,   50,   48,   47,   45,   40,
       39,   37,   25,   22,   14,   11,    7,    3,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "if-else.lex"
#line 25 "if-else.lex"
#include <stdio.h>
#include "if-else.yy.h"

extern void yyerror(const char *);  /* prints grammar violation message */

extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

static void comment(void);
static int check_type(void);
#line 765 "if-else.l.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "if-else.lex"

#line 949 "if-else.l.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 390 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 699 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "if-else.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "if-else.lex"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "if-else.lex"
{ return(A);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "if-else.lex"
{ return(B);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "if-else.lex"
{ return(C);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "if-else.lex"
{ return(D);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "if-else.lex"
{ return(E);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "if-else.lex"
{ return(AUTO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "if-else.lex"
{ return(BREAK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "if-else.lex"
{ return(CASE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "if-else.lex"
{ return(CHAR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "if-else.lex"
{ return(CONST); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "if-else.lex"
{ return(CONTINUE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "if-else.lex"
{ return(DEFAULT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "if-else.lex"
{ return(DO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "if-else.lex"
{ return(DOUBLE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "if-else.lex"
{ return(ELSE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "if-else.lex"
{ return(ENUM); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "if-else.lex"
{ return(EXTERN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "if-else.lex"
{ return(FLOAT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "if-else.lex"
{ return(FOR); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "if-else.lex"
{ return(GOTO); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "if-else.lex"
{ return(IF); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "if-else.lex"
{ return(INLINE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "if-else.lex"
{ return(INT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "if-else.lex"
{ return(LONG); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "if-else.lex"
{ return(REGISTER); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "if-else.lex"
{ return(RESTRICT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "if-else.lex"
{ return(RETURN); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "if-else.lex"
{ return(SHORT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "if-else.lex"
{ return(SIGNED); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "if-else.lex"
{ return(SIZEOF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "if-else.lex"
{ return(STATIC); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "if-else.lex"
{ return(STRUCT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "if-else.lex"
{ return(SWITCH); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "if-else.lex"
{ return(TYPEDEF); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "if-else.lex"
{ return(UNION); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "if-else.lex"
{ return(UNSIGNED); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "if-else.lex"
{ return(VOID); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "if-else.lex"
{ return(VOLATILE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "if-else.lex"
{ return(WHILE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "if-else.lex"
{ return ALIGNAS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "if-else.lex"
{ return ALIGNOF; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "if-else.lex"
{ return ATOMIC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "if-else.lex"
{ return BOOL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "if-else.lex"
{ return COMPLEX; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "if-else.lex"
{ return GENERIC; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "if-else.lex"
{ return IMAGINARY; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "if-else.lex"
{ return NORETURN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "if-else.lex"
{ return STATIC_ASSERT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "if-else.lex"
{ return THREAD_LOCAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "if-else.lex"
{ return FUNC_NAME; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "if-else.lex"
{ return check_type(); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "if-else.lex"
{ return I_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "if-else.lex"
{ return I_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "if-else.lex"
{ return I_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "if-else.lex"
{ return I_CONSTANT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "if-else.lex"
{ return F_CONSTANT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "if-else.lex"
{ return F_CONSTANT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "if-else.lex"
{ return F_CONSTANT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "if-else.lex"
{ return F_CONSTANT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "if-else.lex"
{ return F_CONSTANT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "if-else.lex"
{ return F_CONSTANT; }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 108 "if-else.lex"
{ return STRING_LITERAL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 110 "if-else.lex"
{ return ELLIPSIS; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "if-else.lex"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "if-else.lex"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "if-else.lex"
{ return ADD_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "if-else.lex"
{ return SUB_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "if-else.lex"
{ return MUL_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "if-else.lex"
{ return DIV_ASSIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "if-else.lex"
{ return MOD_ASSIGN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "if-else.lex"
{ return AND_ASSIGN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "if-else.lex"
{ return XOR_ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "if-else.lex"
{ return OR_ASSIGN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 121 "if-else.lex"
{ return RIGHT_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "if-else.lex"
{ return LEFT_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 123 "if-else.lex"
{ return INC_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 124 "if-else.lex"
{ return DEC_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 125 "if-else.lex"
{ return PTR_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 126 "if-else.lex"
{ return AND_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 127 "if-else.lex"
{ return OR_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 128 "if-else.lex"
{ return LE_OP; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 129 "if-else.lex"
{ return GE_OP; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 130 "if-else.lex"
{ return EQ_OP; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 131 "if-else.lex"
{ return NE_OP; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 132 "if-else.lex"
{ return ';'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 133 "if-else.lex"
{ return '{'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 134 "if-else.lex"
{ return '}'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 135 "if-else.lex"
{ return ','; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 136 "if-else.lex"
{ return ':'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 137 "if-else.lex"
{ return '='; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 "if-else.lex"
{ return '('; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 139 "if-else.lex"
{ return ')'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 140 "if-else.lex"
{ return '['; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 141 "if-else.lex"
{ return ']'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 142 "if-else.lex"
{ return '.'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 143 "if-else.lex"
{ return '&'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 "if-else.lex"
{ return '!'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 145 "if-else.lex"
{ return '~'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 146 "if-else.lex"
{ return '-'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 147 "if-else.lex"
{ return '+'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 148 "if-else.lex"
{ return '*'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 149 "if-else.lex"
{ return '/'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 150 "if-else.lex"
{ return '%'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 151 "if-else.lex"
{ return '<'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 152 "if-else.lex"
{ return '>'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 153 "if-else.lex"
{ return '^'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 154 "if-else.lex"
{ return '|'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 155 "if-else.lex"
{ return '?'; }
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 157 "if-else.lex"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 158 "if-else.lex"
{ /* discard bad characters */ }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 160 "if-else.lex"
ECHO;
	YY_BREAK
#line 1599 "if-else.l.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 390 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 390 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 389);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 160 "if-else.lex"



int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static void comment(void)
{
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}

